name: 'Check spelling'
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
      - name: Update to latest npm
        run: npm install -g npm@9
      - name: Install dependencies
        run: npm install 
      - uses: streetsidesoftware/cspell-action@v2