name: 'Check spelling'
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: streetsidesoftware/cspell-action@v2