name: 'Check spelling'
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com
          git config --global url."https://".insteadOf git://
          npm install 
      - uses: streetsidesoftware/cspell-action@v2