name: 'Check spelling'
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure Git
        run: git config --global --add url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Configure Git 2
        run: |
          git config --global --add url."https://${{ secrets.ACCESS_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
          git config --global url."https://".insteadOf ssh://
      - name: Install dependencies
        run: npm install 
      - uses: streetsidesoftware/cspell-action@v2